version: '3.8'

networks:
  akpweb_dev:

services:
  akpweb_php-cli:
    container_name: akpweb_php-cli_dev
    build:
      context: ./php-cli
    user: "1000:1000"
    tty: true
    working_dir: /var/www/akpweb
    volumes:
      - ../app:/var/www/akpweb
      - ../theme:/var/www/akpweb/user/themes/akpview
      - ./_cache/composer:/.composer/cache
      - ./_cache/symfony:/.symfony/cache
    networks:
      - akpweb_dev

  akpweb_nginx:
    container_name: akpweb_nginx_dev
    build:
      context: ./nginx
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ../app:/var/www/akpweb:ro
      - ../theme:/var/www/akpweb/user/themes/akpview:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - akpweb_dev

  akpweb_php-fpm:
    container_name: akpweb_php-fpm_dev
    build:
      context: ./php-fpm
    user: "1000:1000"
    tty: true
    volumes:
      - ../app:/var/www/akpweb
      - ../theme:/var/www/akpweb/user/themes/akpview
    networks:
      - akpweb_dev

  akpweb_nodejs-tools:
    container_name: akpweb_nodejs-tools_dev
    build:
      context: ./nodejs-tools
    user: "1000:1000"
    tty: true
    volumes:
      - ../app:/opt
      - ../theme:/opt/user/themes/akpview
    networks:
      - akpweb_dev
