version: '3.8'

networks:
  akpweb_dev:

services:
  akpweb_nginx:
    container_name: akpweb_nginx_dev
    build:
      context: ./nginx
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./../app:/var/www/akpweb:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./var/log/nginx:/var/log/nginx/
    networks:
      - akpweb_dev

  akpweb_php_cli:
    container_name: akpweb_php_cli_dev
    build:
      context: ./php-cli
    user: "1000:1000"
    tty: true
    working_dir: /var/www/akpweb
    volumes:
      - ./../app:/var/www/akpweb
      - ./var/cache/composer:/.composer/cache
      - ./var/cache/symfony:/.symfony/cache
      - ./php/conf/php.development.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - akpweb_dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  akpweb_php_fpm:
    container_name: akpweb_php_fpm_dev
    build:
      context: ./php-fpm
    user: "1000:1000"
    tty: true
    volumes:
      - ./../app:/var/www/akpweb
      - ./php/conf/php.development.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf/fpm.d/akpweb.conf:/usr/local/etc/php-fpm.d/akpweb.conf:ro
      - ./php/conf/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./php/conf/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
    networks:
      - akpweb_dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  akpweb_nodejs_tools:
    container_name: akpweb_nodejs_tools_dev
    build:
      context: ./nodejs-tools
    environment:
      - NODE_ENV=development
    user: "1000:1000"
    tty: true
    volumes:
      - ./../app:/opt
    networks:
      - akpweb_dev
